#ifndef COMMAND_H
#define COMMAND_H

enum class Command : unsigned char
{
	NONE = 0,
	REQUEST_WORD_RAM,
	BEGIN_TRANSFER_BIOS,
	BEGIN_TRANSFER_HOST_MAIN_READ_PAST_END,
	BEGIN_TRANSFER_HOST_MAIN_WAIT_FOR_DSR,
	BEGIN_TRANSFER_HOST_MAIN_WAIT_FOR_EDT,
	BEGIN_TRANSFER_HOST_SUB_READ_PAST_END,
	BEGIN_TRANSFER_HOST_SUB_WAIT_FOR_DSR,
	BEGIN_TRANSFER_HOST_SUB_WAIT_FOR_EDT,
	BEGIN_TRANSFER_DMA_PCM,
	BEGIN_TRANSFER_DMA_PCM_OFFSET_8,
	BEGIN_TRANSFER_DMA_PRG,
	BEGIN_TRANSFER_DMA_PRG_OFFSET_8,
	BEGIN_TRANSFER_DMA_WORD,
	BEGIN_TRANSFER_DMA_WORD_OFFSET_8,
	END_TRANSFER,
};

#endif // COMMAND_H
