#ifndef MODE_H
#define MODE_H

#include <optional>

enum class ModeID
{
	UNCHANGED,
	MAIN_MENU,
	CDC_TEST,
	GRAPHICS_TEST,
	HV_TEST_H_INT_0,
	HV_TEST_H_INT_1,
	HV_TEST_H_INT_223,
	HV_TEST_H_INT_224,
	HV_TEST_H_INT_225,
	HV_TEST_V_START,
	HV_TEST_V_END,
	HV_TEST_H_START,
	HV_TEST_H_END,
	MUSIC_STOP,
	MUSIC_PLAY,
	MUSIC_PLAY_ONCE,
	MUSIC_PLAY_REPEAT,
	MUSIC_PAUSE,
	MUSIC_UNPAUSE,
	MUSIC_SCAN_FAST_FORWARD,
	MUSIC_SCAN_FAST_REVERSE,
	MUSIC_SCAN_OFF,
};

class Mode
{
public:
	virtual ModeID Update() = 0;
};

#endif // MODE_H
