include("${CMAKE_CURRENT_LIST_DIR}/generic.cmake")

set(CLOWNMDSDK_CARTRIDGE 1)

set(CMAKE_C_STANDARD_LIBRARIES "${CMAKE_C_STANDARD_LIBRARIES} -lstubs-cartridge")
set(CMAKE_CXX_STANDARD_LIBRARIES "${CMAKE_CXX_STANDARD_LIBRARIES} -lstubs-cartridge")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${CMAKE_EXE_LINKER_FLAGS_INIT} -T${CLOWNMDSDK_LOCATION}/cartridge.ld")
